// Code generated by ent, DO NOT EDIT.

package sociallink

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sociallink type in the database.
	Label = "social_link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLink holds the string denoting the link field in the database.
	FieldLink = "link"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldSourceDomain holds the string denoting the source_domain field in the database.
	FieldSourceDomain = "source_domain"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the sociallink in the database.
	Table = "social_links"
)

// Columns holds all SQL columns for sociallink fields.
var Columns = []string{
	FieldID,
	FieldLink,
	FieldURL,
	FieldDomain,
	FieldSourceDomain,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the SocialLink queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLink orders the results by the link field.
func ByLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLink, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByDomain orders the results by the domain field.
func ByDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomain, opts...).ToFunc()
}

// BySourceDomain orders the results by the source_domain field.
func BySourceDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceDomain, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
