// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SocialLinksColumns holds the columns for the "social_links" table.
	SocialLinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "link", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "domain", Type: field.TypeString, Nullable: true},
		{Name: "source_domain", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SocialLinksTable holds the schema information for the "social_links" table.
	SocialLinksTable = &schema.Table{
		Name:       "social_links",
		Columns:    SocialLinksColumns,
		PrimaryKey: []*schema.Column{SocialLinksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sociallink_url",
				Unique:  true,
				Columns: []*schema.Column{SocialLinksColumns[2]},
			},
			{
				Name:    "sociallink_domain",
				Unique:  false,
				Columns: []*schema.Column{SocialLinksColumns[3]},
			},
			{
				Name:    "sociallink_source_domain",
				Unique:  false,
				Columns: []*schema.Column{SocialLinksColumns[4]},
			},
			{
				Name:    "sociallink_domain_created_at",
				Unique:  false,
				Columns: []*schema.Column{SocialLinksColumns[3], SocialLinksColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SocialLinksTable,
	}
)

func init() {
}
