// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SocialLink is the predicate function for sociallink builders.
type SocialLink func(*sql.Selector)
